name: somospie
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - curl
  - gdal
  - pip
  - pip:
    - pandas
    - pyspark
    - findspark
    - scikit-learn
    - matplotlib
    - grass-session